### ISSUE TITLE
This erros happens

### ISSUE THREAD

**Issue by fnxln** [Seytonic/Duckduino-microSD#3]
sketch_feb22a.ino: In function ‘void setup()’:
sketch_feb22a.ino:40:23: error: no matching function for call to ‘SDClass::open(String&)’
sketch_feb22a.ino:40:23: note: candidate is:
In file included from sketch_feb22a.ino:11:0:
/usr/share/arduino/libraries/SD/SD.h:87:8: note: File SDClass::open(const char*, uint8_t)
   File open(const char *filename, uint8_t mode = FILE_READ);
        ^
/usr/share/arduino/libraries/SD/SD.h:87:8: note:   no known conversion for argument 1 from ‘String’ to ‘const char*’
What i do?

**Comment by krak3n77** [comment]
What arduino are you using?
